### ISSUE TITLE
which encoding for the Strings?

### ISSUE THREAD

**Issue by cmacdonald** [Joseph94m/MatchZooIntegration#1]
https://github.com/Joseph94m/MatchZooIntegration/blob/744352ea3a571b637c2ed0ca5946c914f8f19c46/IRcourseHM-master/src/main/java/uk/ac/gla/dcs/dsms/MZCommunicator.java#L135

**Comment by Joseph94m** [comment]
Fixed, encoding is now specified to be 'ISO-8859-1'. The default was UTF-8 but it is not needed since we are only sending numbers and letters. This change should also reduce the size of the messages sent across the network.

**Comment by cmacdonald** [comment]
UTF-8 is safer. Terrier supports multiple languages.

**Comment by cmacdonald** [comment]
also on the use of the `new String(byte[])` constructor.
